### ISSUE TITLE
Cannot Sign Up

### ISSUE THREAD

**Issue by mciocchi** [mbonassa/capstone#138]
I get the following error when clicking "Sign up," even with cookies and notifications enabled.

This is in Firefox 57.0.4 (64-bit)

![login-issue](https://user-images.githubusercontent.com/491288/37156263-95bf21f6-22b3-11e8-9c02-de26baa51415.png)

**Comment by sammorrow** [comment]
The site requires push notifications in order to sign up, which are unavailable on HTTP. Site's been updated to force HTTPS.
